#ifndef _ILI9341_t3_font_AlegreyaSansSC-BlackItalic_
#define _ILI9341_t3_font_AlegreyaSansSC-BlackItalic_

#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t AlegreyaSansSCBlack_8_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCBlack_9_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCBlack_10_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCBlack_11_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCBlack_12_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCBlack_13_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCBlack_14_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCBlack_16_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCBlack_18_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCBlack_20_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCBlack_24_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCBlack_28_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCBlack_32_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCBlack_40_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCBlack_48_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCBlack_60_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCBlack_72_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCBlack_96_Bold_Italic;

#ifdef __cplusplus
} // extern "C"
#endif

#endif
