#ifndef _ILI9341_t3_font_AlegreyaSansSC-ExtraBoldItalic_
#define _ILI9341_t3_font_AlegreyaSansSC-ExtraBoldItalic_

#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t AlegreyaSansSCExtraBold_8_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCExtraBold_9_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCExtraBold_10_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCExtraBold_11_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCExtraBold_12_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCExtraBold_13_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCExtraBold_14_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCExtraBold_16_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCExtraBold_18_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCExtraBold_20_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCExtraBold_24_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCExtraBold_28_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCExtraBold_32_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCExtraBold_40_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCExtraBold_48_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCExtraBold_60_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCExtraBold_72_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansSCExtraBold_96_Bold_Italic;

#ifdef __cplusplus
} // extern "C"
#endif

#endif
