#ifndef _ILI9341_t3_font_AlegreyaSans-ExtraBoldItalic_
#define _ILI9341_t3_font_AlegreyaSans-ExtraBoldItalic_

#include "ILI9341_t3.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const ILI9341_t3_font_t AlegreyaSansExtraBold_8_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansExtraBold_9_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansExtraBold_10_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansExtraBold_11_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansExtraBold_12_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansExtraBold_13_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansExtraBold_14_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansExtraBold_16_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansExtraBold_18_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansExtraBold_20_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansExtraBold_24_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansExtraBold_28_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansExtraBold_32_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansExtraBold_40_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansExtraBold_48_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansExtraBold_60_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansExtraBold_72_Bold_Italic;
extern const ILI9341_t3_font_t AlegreyaSansExtraBold_96_Bold_Italic;

#ifdef __cplusplus
} // extern "C"
#endif

#endif
